//
// Autogenerated by Thrift Compiler (0.11.0)
//
// DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
//
"use strict";

var thrift = require('thrift');
var Thrift = thrift.Thrift;
var Q = thrift.Q;


var ttypes = module.exports = {};
var Gif = module.exports.Gif = function(args) {
  this.id = null;
  this.urlGif = null;
  this.contador = null;
  this.descripcion = null;
  if (args) {
    if (args.id !== undefined && args.id !== null) {
      this.id = args.id;
    }
    if (args.urlGif !== undefined && args.urlGif !== null) {
      this.urlGif = args.urlGif;
    }
    if (args.contador !== undefined && args.contador !== null) {
      this.contador = args.contador;
    }
    if (args.descripcion !== undefined && args.descripcion !== null) {
      this.descripcion = args.descripcion;
    }
  }
};
Gif.prototype = {};
Gif.prototype.read = function(input) {
  input.readStructBegin();
  while (true)
  {
    var ret = input.readFieldBegin();
    var fname = ret.fname;
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid)
    {
      case 1:
      if (ftype == Thrift.Type.I32) {
        this.id = input.readI32();
      } else {
        input.skip(ftype);
      }
      break;
      case 2:
      if (ftype == Thrift.Type.STRING) {
        this.urlGif = input.readString();
      } else {
        input.skip(ftype);
      }
      break;
      case 3:
      if (ftype == Thrift.Type.I32) {
        this.contador = input.readI32();
      } else {
        input.skip(ftype);
      }
      break;
      case 4:
      if (ftype == Thrift.Type.STRING) {
        this.descripcion = input.readString();
      } else {
        input.skip(ftype);
      }
      break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

Gif.prototype.write = function(output) {
  output.writeStructBegin('Gif');
  if (this.id !== null && this.id !== undefined) {
    output.writeFieldBegin('id', Thrift.Type.I32, 1);
    output.writeI32(this.id);
    output.writeFieldEnd();
  }
  if (this.urlGif !== null && this.urlGif !== undefined) {
    output.writeFieldBegin('urlGif', Thrift.Type.STRING, 2);
    output.writeString(this.urlGif);
    output.writeFieldEnd();
  }
  if (this.contador !== null && this.contador !== undefined) {
    output.writeFieldBegin('contador', Thrift.Type.I32, 3);
    output.writeI32(this.contador);
    output.writeFieldEnd();
  }
  if (this.descripcion !== null && this.descripcion !== undefined) {
    output.writeFieldBegin('descripcion', Thrift.Type.STRING, 4);
    output.writeString(this.descripcion);
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

